### ISSUE TITLE
Exception when returning a RXJava3 Completable from a HTTP client

### ISSUE THREAD

**Issue by jmongard** [micronaut-projects/micronaut-rxjava3#1]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a HTTP client returning a RXJava3Completable
2. Inject the client in a controller
3. Call the method from the controller
4. Call the controller from a test

Both RXJava3 Completable and RXJava2 Flowable implements Producer so Micronaut think they can be converted when looking through converters in `io.micronaut.core.convert.DefaultConversionService.findTypeConverter(Class<?>, Class<T>, String)` but there is no explicit conversation for this registered by RxJava3ConverterRegistrar

### Expected Behaviour

The http client returns a rxjava3 Completable

### Actual Behaviour

```
java.lang.ClassCastException: io.micronaut.rxjava3.instrument.RxInstrumentedFlowable cannot be cast to io.reactivex.Flowable
	at io.micronaut.retry.intercept.RecoveryInterceptor.fallbackForReactiveType(RecoveryInterceptor.java:91)
	at io.micronaut.retry.intercept.RecoveryInterceptor.intercept(RecoveryInterceptor.java:78)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at ExampleClient$Intercepted.index(Unknown Source)
```

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.0.0.M3
- **JDK Version:** 1.80_252

### Example Application
```
@io.micronaut.http.client.annotation.Client("http://www.example.com")
public interface ExampleClient {
    @io.micronaut.http.annotation.Get(uri = "/")
    public io.reactivex.rxjava3.core.Completable index();
}
```

**Comment by jameskleeh** [comment]
@jmongard Please test with Micronaut 2.2.1

**Comment by jmongard** [comment]
It works now. This bug is a duplicate of micronaut-projects/micronaut-core#4452 that you just fixed.
