### ISSUE TITLE
io.reactivex.rxjava3.core.Single with @CircuitBreaker will result in broken response

### ISSUE THREAD

**Issue by artfable** [micronaut-projects/micronaut-rxjava3#87]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Put `@CircuitBreaker` with an endpoint that return Single and throw an exception
2. Make request to the endpoint
3. Make second request while CircuitBreaker is open

### Expected Behaviour

Second request failed in the same way as the first one (same HTTP Status code, same response body)

### Actual Behaviour

Second request will have 200 OK HTTP Status code and symbol `[` in response body

### Environment Information

- **Micronaut Version:** 2.4.1
- **JDK Version:** Oracle jdk 15

### Example Application

-  https://github.com/artfable/micronaut-test

**Comment by jameskleeh** [comment]
I cannot reproduce this with 3.1.3

**Comment by o-shevchenko** [comment]
Hi
Looks like I faced the same problem for `CircuitBreaker` when I use Reactor Publisher.
What was the resolution to your problem? Per this: https://stackoverflow.com/questions/66804625/wrong-behaviour-for-circuitbreaker-in-micronaut
I tried to replay `Publisher` return type with `Mono` but it didn't help.

```kotlin
@Client(
    value = "\${url}",
    path = "\${path}",
    errorType = ErrorInfo::class
)
@CircuitBreaker(
    attempts = "\${retry.attempts}",
    delay = "\${retry.delay}",
    multiplier = "\${retry.multiplier}",
    reset = "\${.retr.reset}"
)
@Headers(Header(name = ACCEPT, value = "application/json"))
interface MyClient {

    @Post("/test")
    fun test(@Body dto: Dto): Publisher<Any>
}
....
@Post(uri = "/test")
    fun test(
        @Body dto: dto
    ): Publisher<MutableHttpResponse<Any>> {
        return service.test(dto)
            .toMono()
            .map { HttpResponse.ok(it) }
            .defaultIfEmpty(HttpResponse.ok())
            .onErrorResume(TestException::class.java) { exception ->
                Mono.just(HttpResponse.badRequest(JsonError(exception.message)))
            }
    }
```

**Comment by o-shevchenko** [comment]
Created issue and added sample project with reproduce here: https://github.com/micronaut-projects/micronaut-reactor/issues/197
